##### diamond overlap --> see /n/home02/rmehta/diamond4_5asa_hsph.sh in the cannon cluster ####

library(stringr)
library(dplyr)
library(tidyr)

#read in diamond output generated by ".sh" file
diamondoutp <- read.table("/home/rsm34/5asabb3/reviews/keyfiles/out6.tsv",header=F,sep="\t")
header <- c("query.accession","target.accession","identity","length","mismatches","openings","qstart","qend","tstart","tend","evalue","bitscore")
colnames(diamondoutp)<- header
head(diamondoutp) 
diamondoutp$names <- gsub("\\|.*","",diamondoutp$target.accession)

size<-(diamondoutp) %>% distinct(names)
dim(size) #5690 unique unirefs

#read in all rna names 
mtxall <- read.table("/home/rsm34/5asabb3/archive/RNA_uniref/rnauni_subset_bb3.txt",header=T,sep="\t") 
mtxall_2 <- data.frame(names(mtxall))
names(mtxall_2) <- "names"
dim(mtxall_2)

write.table(mtxall_2, "/home/rsm34/5asabb3/reviews/keyfiles/allmtxnames.txt", sep="\t", quote=FALSE,row.names=FALSE) 


#read in all dna names
dnaall <- read.table("/home/rsm34/5asabb3/archive/DNA_uniref/DNAunirefproptable2.txt",header=T,sep="\t") %>% select(ID) %>% rename(names=ID) 
dim(dnaall)


diamond_all <- inner_join(diamondoutp,mtxall_2,by="names") 
dim(diamond_all) #0

diamond_dnaall <- inner_join(diamondoutp,dnaall,by="names") 
dim(diamond_dnaall) 
diamondsubset<- diamond_dnaall %>% distinct(names) #16 

diamondsubset$uniprotID <- str_replace(diamondsubset$names,"UniRef90_","")
write.table(diamondsubset, "diamond_uniref90_simmer.txt", sep="\t", quote=FALSE,row.names=FALSE)


##########  read in blastp 80% to oscillobacter protein ######

oscillo80p <- read.table("/home/rsm34/5asabb3/intermediate_files/oscillo80pcentblastp.txt",header=T,sep="\t")

blastp_80 <- inner_join(oscillo80p,mtxall_2,by="names") 
dim(blastp_80) #5
#
#            names
#1 UniRef90_U2QX51
#2 UniRef90_R6TIX3
#3 UniRef90_R5CY66
#4 UniRef90_R6CZ24
#5 UniRef90_T5S060


